### ISSUE TITLE
Rules for auto-generating an sfz.tmLanguage.json file from syntax.yml

### ISSUE THREAD

**Issue by kmturley** [jokela/vscode-sfz#5]
**Background**
SFZ format is defined by the community in a YAML file here:
https://raw.githubusercontent.com/sfzformat/sfzformat.github.io/source/_data/sfz/syntax.yml

You have a syntax file which manually needs to be updated with changes here:
https://github.com/jokela/vscode-sfz/blob/master/syntaxes/sfz.tmLanguage.json

I have prototyped a way to autogenerated the file:
https://github.com/kmturley/sfz-syntax-highlighters

The result so far can be seen here:
https://github.com/kmturley/sfz-syntax-highlighters/blob/gh-pages/tmLanguage-modified.json

**Problem**
Both syntax.yml and sfz.tmLanguage.json files have been manually updated and therfore they have deviated and don't line-up one to one. In addition, you have RegEx rules on some attributes but not on others.

When I try to diff your original, vs the auto-generated version there are so many changes it is hard to see where the issues are:
<img width="1482" alt="Screenshot 2023-02-23 at 9 02 28 PM" src="https://user-images.githubusercontent.com/1710493/221096292-8b40827a-93b3-4090-9baa-89601a0e4eed.png">

**Suggested solution**
Document the rules used to generate your version of the file?
I can then use those rules to update the code and generate a functioning file for your plugin.
Thanks!

**Comment by jokela** [comment]
Hi, @redtide contacted me a couple of weeks ago with a similar question. He's working on a python-based generator.

My tmLanguage.json file was manually written—I don't think syntax.yml existed yet and SFZ itself seemed static. At the time, the best I could do was create a spreadsheet from available sources and use it as a checklist.

Your work looks really promising and you've clearly put a lot of time into it. It would be cool if the community could create a YAML->tmLanguage generator as well as a YAML->test.sfz.  I can add any interested collaborators to the project.

**Comment by kmturley** [comment]
Thanks for responding. I tried my best to get the two files close as possible.
However ultimately as both files are hand-coded there are too many differences for me to accurately match them.

I think a better long-term solution would be to autogenerate `syntax.yml` from a suite of tests run on different SFZ players.
If the player passes the test, then it gets added to the opcode list
There are ways to test vst plugins using automated command line scripts.

Anyway that is not a solution for here. So will close this issue!
